site_name: My Project Documentation

theme:
  name: material
  palette:
    - scheme: slate  # 設置深色主題
  features:
    - navigation.tabs
    - navigation.expand

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          docstring_style: google  
          paths:
            - src 

nav:
  - Home: index.md
  - API Documentation:
      - GWR Module: "reference/gwr.md"

